fix solo machine proof height sequence mismatch in connection handshake verification
cosmos/ibc pull request #570
Opened 2021-05-05 11:08 UTC by colin-axner

ref: #562 

Addresses one problem outlined in the issue above. Enforces that the proof height is equivalent to the current client state sequence. 
**NOTE**: `VerifyClientState` is missing from ICS 03-connection as noted in #525. It is assumed that it will be inserted after `VerifyConnection` and before `VerifyClientConsensusState`

2021-05-05 11:19 UTC, emadami3060 approved these changes

2021-05-06 08:25 UTC, cwgoes requested changes
We should explain the `height + 2` bit

2021-05-06 08:25 UTC, cwgoes commented on spec/client/ics-006-solo-machine-client/README.md
> +    abortTransactionUnless(height + 2 == clientState.consensusState.sequence)
this merits a comment or explanation somewhere as to why it is `height + 2`

2021-05-06 09:16 UTC, emadami3060 approved these changes

2021-05-07 10:01 UTC, colin-axner commented on spec/client/ics-006-solo-machine-client/README.md
> +    abortTransactionUnless(height + 2 == clientState.consensusState.sequence)
Did you read through the discussion in #562? I agree it is strange to hard code the delta in the verify function, but I don't see a more elegant solution. The proof height incrementing for each verification call is unique to the solo machine and thus cannot be brought into core IBC. Non-unique sequences is misbehaviour for the solo machine. Proof height may be meaningful to core IBC now or later and thus needs to be verified

2021-05-09 21:12 UTC, cwgoes approved these changes
ACK

2021-05-11 21:01 UTC, merged

2021-05-11 21:01 UTC, cwgoes commented
(merging with requisite 2/3 quorum from IBC spec committee)