ICS-29: updates based on current implementation
cosmos/ibc pull request #779
Opened 2022-06-29 20:29 UTC by crodriguezvega

2022-06-30 10:54 UTC, AdityaSripal requested changes
Nice work @crodriguezvega , a couple quick changes

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +interface Acknowledgement {
This needs to be included since it is being sent over the wire

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +        app.onChanOpenTry(
```suggestion
        return app.onChanOpenTry(
```

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +    app.onChanOpenTry(
```suggestion
    return app.onChanOpenTry(
```

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +    app.onChanOpenInit(
```suggestion
    return app.onChanOpenInit(
```

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +        app.onChanOpenAck(
```suggestion
        return app.onChanOpenAck(
```

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +    app.onChanOpenAck(
```suggestion
    return app.onChanOpenAck(
```

2022-06-30 10:54 UTC, AdityaSripal commented on spec/app/ics-029-fee-payment/README.md
> +    app.onChanOpenConfirm(portIdentifier, channelIdentifier)
```suggestion
    return app.onChanOpenConfirm(portIdentifier, channelIdentifier)
```

2022-07-04 11:02 UTC, AdityaSripal approved these changes
Thanks @crodriguezvega !

2022-07-05 08:18 UTC, mpoke approved these changes
LGTM

2022-07-05 08:18 UTC, mpoke commented on spec/app/ics-029-fee-payment/README.md
> +// This ensures they will be properly compensated for forward relaying since destination chain must send back relayer's source address (counterparty payee address) in acknowledgement
nit: break the comments on multiple lines to make it easier to read

2022-07-05 08:27 UTC, crodriguezvega commented on spec/app/ics-029-fee-payment/README.md
> +- It must allow relayers to register their counterparty payee address.
This is the `source address`.

2022-07-05 19:49 UTC, merged