ICS7: Refactor based on 02-client refactor
cosmos/ibc pull request #817
Opened 2022-08-11 16:00 UTC by AdityaSripal

2022-08-25 12:52 UTC, mpoke requested changes

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    assert(verify(
`verify()` is undefined.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +        verifyHeader(clientState, clientMsg.h2)
In ibc-go, `verifyMisbehaviour` is called here instead, i.e., https://github.com/cosmos/ibc-go/blob/b6dd7244075b4e56daf4ddcb9b6f7d622eb3a048/modules/light-clients/07-tendermint/update.go#L29

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +function checkForMisbehaviour(
`checkForMisbehaviour` has only `ClientMessage` as a param in ICS-2, i.e., 
```
type checkForMisbehaviour = (ClientMessage) => bool
```

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +        if consensusState != nil && consensusState.commitmentRoot != header.AppHash {
`header.AppHash` is not defined. Should this be `header. commitmentRoot` instead?

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +        nextConsState = getNextConsensusState(header.Height)
`getPreviousConsensusState` and `getNextConsensusState` not defined

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +        if prevConsState.timestamp >= header.timestamp {
Why not check `if prevConsState != nil && ...` as for  `nextConsState`?

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +### CheckForMisbehaviour
ditto: "Misbehaviour predicate" instead of "CheckForMisbehaviour"

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +function updateState(
ditto: In ICS-2, `updateState()` doesn't have `clientState` as a param.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +      clientState.latestTimestamp = header.timestamp
In ibc-go, there are no `validatorSet` and `latestTimestamp` fields.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    consensusState = get("clients/{identifier}/consensusStates/{header.trustedHeight}")
`{identifier}` is not defined. Similar in multiple places throughout this spec.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +      set("clients/{identifier}", clientState)
In [ICS-24](https://github.com/cosmos/ibc/blob/main/spec/core/ics-024-host-requirements/README.md#path-space), the key for `ClientState`s is defined as `clients/{identifier}/clientState`

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
>      set("clients/{identifier}/processedHeights/{header.height}", currentHeight())
Neither paths are defined in ICS-24.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +function updateStateOnMisbehaviour(
ditto: n ICS-2, `updateStateOnMisbehaviour()` doesn't have `clientState` as a param.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
>      set("clients/{identifier}", clientState)
ditto: incorrect path

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    misbehaviour = Misbehaviour(clientMessage)
`misbehaviour` var never used; `Misbehaviour()` function not defined

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
>      root = get("clients/{identifier}/consensusStates/{height}")
Cf. ICS-24, this is a `ConsensusState`.

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    assert(root.verifyMembership(path, value, proof))
Cf. [ICS-23](https://github.com/cosmos/ibc/blob/main/spec/core/ics-023-vector-commitments/README.md#proof-verification), `verifyMembership` has the following signature:
```typescript
type verifyMembership = (root: CommitmentRoot, proof: CommitmentProof, path: CommitmentPath, value: Value) => boolean
```

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
>      root = get("clients/{identifier}/consensusStates/{height}")
ditto

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    assert(root.verifyMembership(path, proof))
ditto

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    // verify that the provided consensus state has been stored
```suggestion
    // verify that <path, value> has been stored
```

2022-08-25 12:52 UTC, mpoke commented on spec/client/ics-007-tendermint-client/README.md
> +    // verify that the provided consensus state has been stored
```suggestion
    // verify that nothing has been stored at path
```

2022-09-05 12:07 UTC, AdityaSripal commented on spec/client/ics-007-tendermint-client/README.md
> +    clientState = get("clients/{header.identifier}/clientState)
```suggestion
    clientState = get("clients/{header.identifier}/clientState")
```

2022-09-05 12:07 UTC, AdityaSripal commented on spec/client/ics-007-tendermint-client/README.md
> +    clientState = get("clients/{clientMsg.identifier}/clientState)
```suggestion
    clientState = get("clients/{clientMsg.identifier}/clientState")
```

2022-09-06 10:05 UTC, mpoke approved these changes

2022-09-06 13:13 UTC, merged