add note about controller modules not doing anything in onRecvPacket
cosmos/ibc pull request #845
Opened 2022-10-03 20:33 UTC by crodriguezvega

closes: #603

2022-10-05 14:12 UTC, mpoke requested changes

2022-10-05 14:12 UTC, mpoke commented on spec/app/ics-027-interchain-accounts/README.md
> +Note that interchain accounts controller modules should not execute any logic upon packet receipt, i.e. the `OnRecvPacket` callback should not be called, and in case it is called, it should simply re
I think it would be clearer to just add the OnRecvPacket pseudocode with the error acknowledgement returned.

2022-10-10 16:43 UTC, colin-axner approved these changes
Thanks @crodriguezvega

2022-10-12 11:44 UTC, mpoke approved these changes
LGTM

2022-10-12 11:44 UTC, merged